{% set name = "crawl4ai" %}
{% set version = "0.3.743" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crawl4ai-{{ version }}.tar.gz
  sha256: 429e7703855102bc3422cf3538e61e2fe12b2d0b7fb696e87ee8253349aa467a

build:
  entry_points:
    - crawl4ai-download-models=crawl4ai.model_loader:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - aiofiles >=24.0,<25.dev0
    - colorama >=0.4,<1.dev0
    - python-xxhash >=3.4,<4.dev0
    - rank-bm25 >=0.2,<1.dev0
    - snowballstemmer >=2.2,<3.dev0
    - tf-playwright-stealth >=1.0,<2.dev0
    - playwright-stealth >=1.0,<2.dev0
    - playwright <1.48,>=1.47
    - python >=3.7
    - aiosqlite >=0.20,<1.dev0
    - html2text >=2024.2,<2025.dev0
    - lxml >=5.3,<6.dev0
    - litellm >=1.48,<2.dev0
    - numpy <3,>=1.26.0
    - pillow >=10.4,<11.dev0
    - playwright-python ==1.47.0
    - python-dotenv >=1.0,<2.dev0
    - requests >=2.26,<3.dev0
    - beautifulsoup4 >=4.12,<5.dev0

test:
  imports:
    - crawl4ai
  commands:
    - pip check
    - crawl4ai-download-models --help
  requires:
    - pip

about:
  home: https://github.com/unclecode/crawl4ai
  summary: 'ðŸ”¥ðŸ•·ï¸ Crawl4AI: Open-source LLM Friendly Web Crawler & scraper'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
