context:
  version: 0.7.6
  python_min: '3.10'

package:
  name: crawl4ai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/crawl4ai/crawl4ai-${{ version }}.tar.gz
    sha256: cdcf86db45863ee0c155b9969be292fbe50dbc8756e6ddae2cbc7e919656892a

build:
  number: 0
  python:
    entry_points:
      - crawl4ai-download-models=crawl4ai.model_loader:main
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - aiosqlite >=0.20,<1.dev0
    - lxml >=5.3,<6.dev0
    - litellm >=1.53.1
    - numpy >=1.26.0,<3
    - pillow >=10.4
    - python-dotenv >=1.0,<2.dev0
    - requests >=2.26,<3.dev0
    - beautifulsoup4 >=4.12,<5.dev0
    - tf-playwright-stealth >=1.1.0
    - python-xxhash >=3.4,<4.dev0
    - rank-bm25 >=0.2,<1.dev0
    - aiofiles >=24.1.0
    - snowballstemmer >=2.2,<3.dev0
    - pydantic >=2.10
    - pyopenssl >=24.3.0
    - psutil >=6.1.1
    - nltk >=3.9.1
    - rich >=13.9.4
    - cssselect >=1.2.0
    - httpx >=0.27.2
    - fake-useragent >=2.0.3
    - humanize >=4.10.0
    - chardet >=5.2.0
    - lark >=1.2.2
    - alphashape >=1.3.1
    - shapely >=2.0.0
    - patchright >=1.49.0
    - anyio >=4.0.0
    - playwright >=1.49.0
    - click >=8.1.7
    - brotli >=1.1.0
    - pyyaml >=6.0
    - aiohttp >=3.11.11
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - crawl4ai
      pip_check: true
  - script:
      - crawl4ai-download-models --help

about:
  homepage: https://github.com/unclecode/crawl4ai
  summary: '🔥🕷️ Crawl4AI: Open-source LLM Friendly Web Crawler & scraper'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - moritzwilksch
